/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardPageRouteImport } from './routes/DashboardPage'
import { Route as IndexRouteImport } from './routes/index'

const DashboardPageRoute = DashboardPageRouteImport.update({
  id: '/DashboardPage',
  path: '/DashboardPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/DashboardPage': typeof DashboardPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/DashboardPage': typeof DashboardPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/DashboardPage': typeof DashboardPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/DashboardPage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/DashboardPage'
  id: '__root__' | '/' | '/DashboardPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardPageRoute: typeof DashboardPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/DashboardPage': {
      id: '/DashboardPage'
      path: '/DashboardPage'
      fullPath: '/DashboardPage'
      preLoaderRoute: typeof DashboardPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardPageRoute: DashboardPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
